USE [master]
GO
/****** Object:  Database [JAVA2]    Script Date: 25.07.2018 19:43:55 ******/
CREATE DATABASE [JAVA2]
GO
ALTER DATABASE [JAVA2] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [JAVA2].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [JAVA2] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [JAVA2] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [JAVA2] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [JAVA2] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [JAVA2] SET ARITHABORT OFF 
GO
ALTER DATABASE [JAVA2] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [JAVA2] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [JAVA2] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [JAVA2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [JAVA2] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [JAVA2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [JAVA2] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [JAVA2] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [JAVA2] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [JAVA2] SET  ENABLE_BROKER 
GO
ALTER DATABASE [JAVA2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [JAVA2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [JAVA2] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [JAVA2] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [JAVA2] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [JAVA2] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [JAVA2] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [JAVA2] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [JAVA2] SET  MULTI_USER 
GO
ALTER DATABASE [JAVA2] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [JAVA2] SET DB_CHAINING OFF 
GO
ALTER DATABASE [JAVA2] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [JAVA2] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [JAVA2] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [JAVA2] SET QUERY_STORE = OFF
GO
USE [JAVA2]
GO
ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [JAVA2]
GO
/****** Object:  Table [dbo].[Car]    Script Date: 25.07.2018 19:43:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Car](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Mark] [nvarchar](50) NOT NULL,
	[Model] [nvarchar](50) NOT NULL,
	[MotorCapacity] [int] NOT NULL,
	[Color] [nvarchar](max) NOT NULL,
	[FuelTypeId] [int] NOT NULL,
	[GearboxTypeId] [int] NOT NULL,
 CONSTRAINT [PK_Car] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CarStatus]    Script Date: 25.07.2018 19:43:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CarStatus](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_CarStatus] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[FuelType]    Script Date: 25.07.2018 19:43:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FuelType](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Type] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_FuelType] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[GearboxType]    Script Date: 25.07.2018 19:43:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GearboxType](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Type] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_GearboxType] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HomeAddress]    Script Date: 25.07.2018 19:43:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HomeAddress](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Country] [nvarchar](250) NOT NULL,
	[City] [nvarchar](250) NOT NULL,
	[Street] [nvarchar](250) NOT NULL,
	[Number] [nchar](250) NOT NULL,
 CONSTRAINT [PK_HomeAddress] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Rent]    Script Date: 25.07.2018 19:43:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Rent](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ClientId] [int] NOT NULL,
	[CarId] [int] NOT NULL,
	[DateFrom] [datetime] NOT NULL,
	[DateTo] [datetime] NOT NULL,
	[CarStatusId] [int] NOT NULL,
	[ReserveDate] [datetime] NULL,
	[ReturnDate] [datetime] NULL,
	[OperatorIdGaveCar] [int] NOT NULL,
	[OperatorIdAcceptCar] [int] NOT NULL,
 CONSTRAINT [PK_Rent] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[User]    Script Date: 25.07.2018 19:43:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](max) NOT NULL,
	[SecondName] [nvarchar](max) NOT NULL,
	[BirthDate] [datetime] NOT NULL,
	[HomeAddressId] [int] NOT NULL,
	[UserTypeId] [int] NOT NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserType]    Script Date: 25.07.2018 19:43:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserType](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Type] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_UserType] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[CarStatus] ON 

INSERT [dbo].[CarStatus] ([Id], [Name]) VALUES (1, N'Reserved')
INSERT [dbo].[CarStatus] ([Id], [Name]) VALUES (2, N'Running')
INSERT [dbo].[CarStatus] ([Id], [Name]) VALUES (3, N'Returned')
INSERT [dbo].[CarStatus] ([Id], [Name]) VALUES (4, N'Canceled')
SET IDENTITY_INSERT [dbo].[CarStatus] OFF
SET IDENTITY_INSERT [dbo].[FuelType] ON 

INSERT [dbo].[FuelType] ([Id], [Type]) VALUES (1, N'Diesel')
INSERT [dbo].[FuelType] ([Id], [Type]) VALUES (2, N'Petrol')
INSERT [dbo].[FuelType] ([Id], [Type]) VALUES (3, N'Electro')
INSERT [dbo].[FuelType] ([Id], [Type]) VALUES (4, N'Hybrid')
SET IDENTITY_INSERT [dbo].[FuelType] OFF
SET IDENTITY_INSERT [dbo].[GearboxType] ON 

INSERT [dbo].[GearboxType] ([Id], [Type]) VALUES (1, N'Manual')
INSERT [dbo].[GearboxType] ([Id], [Type]) VALUES (2, N'Automatic')
SET IDENTITY_INSERT [dbo].[GearboxType] OFF
SET IDENTITY_INSERT [dbo].[UserType] ON 

INSERT [dbo].[UserType] ([Id], [Type]) VALUES (1, N'Client')
INSERT [dbo].[UserType] ([Id], [Type]) VALUES (2, N'Operator')
SET IDENTITY_INSERT [dbo].[UserType] OFF
ALTER TABLE [dbo].[Car]  WITH CHECK ADD  CONSTRAINT [FK_Car_FuelType] FOREIGN KEY([FuelTypeId])
REFERENCES [dbo].[FuelType] ([Id])
GO
ALTER TABLE [dbo].[Car] CHECK CONSTRAINT [FK_Car_FuelType]
GO
ALTER TABLE [dbo].[Car]  WITH CHECK ADD  CONSTRAINT [FK_Car_GearboxType] FOREIGN KEY([GearboxTypeId])
REFERENCES [dbo].[GearboxType] ([Id])
GO
ALTER TABLE [dbo].[Car] CHECK CONSTRAINT [FK_Car_GearboxType]
GO
ALTER TABLE [dbo].[Rent]  WITH CHECK ADD  CONSTRAINT [FK_Rent_Car] FOREIGN KEY([CarId])
REFERENCES [dbo].[Car] ([Id])
GO
ALTER TABLE [dbo].[Rent] CHECK CONSTRAINT [FK_Rent_Car]
GO
ALTER TABLE [dbo].[Rent]  WITH CHECK ADD  CONSTRAINT [FK_Rent_CarStatus] FOREIGN KEY([CarStatusId])
REFERENCES [dbo].[CarStatus] ([Id])
GO
ALTER TABLE [dbo].[Rent] CHECK CONSTRAINT [FK_Rent_CarStatus]
GO
ALTER TABLE [dbo].[Rent]  WITH CHECK ADD  CONSTRAINT [FK_Rent_User] FOREIGN KEY([ClientId])
REFERENCES [dbo].[User] ([Id])
GO
ALTER TABLE [dbo].[Rent] CHECK CONSTRAINT [FK_Rent_User]
GO
ALTER TABLE [dbo].[User]  WITH CHECK ADD  CONSTRAINT [FK_User_HomeAddress] FOREIGN KEY([HomeAddressId])
REFERENCES [dbo].[HomeAddress] ([Id])
GO
ALTER TABLE [dbo].[User] CHECK CONSTRAINT [FK_User_HomeAddress]
GO
ALTER TABLE [dbo].[User]  WITH CHECK ADD  CONSTRAINT [FK_User_UserType] FOREIGN KEY([UserTypeId])
REFERENCES [dbo].[UserType] ([Id])
GO
ALTER TABLE [dbo].[User] CHECK CONSTRAINT [FK_User_UserType]
GO
USE [master]
GO
ALTER DATABASE [JAVA2] SET  READ_WRITE 
GO
